### ISSUE TITLE
Rate Limiting?

### ISSUE THREAD

**Issue by AlanOC91** [UserSina/YGOCards_Downloader#1]
Hey there!

Owner of YGOPRODeck here. Neat script!
I have to ask, is there any sort of rate limit implemented in this script when pulling images? 

A while ago now my site halted to a crawl and it was due to someone running a python script to pull all the images from the site. I had to set the site to high security mode and implement heavy rate limits across the site as it was becoming unusable. Temporarily of course.

So I'm small bit concerned about this as I may have to re-enable some of that protection which unfortunately will affect all my site users which is why I'd like to ask here first before making any changes.

Thanks! 
Looking forward to hearing back.
Alan

**Comment by AlanOC91** [comment]
Also I'd massively prefer if the script could be changed to point to our secondary Google cloud server which we use for our API. You wouldn't have to change much, it still sees it via ID. 

Example: https://storage.googleapis.com/ygoprodeck.com/pics/27551.jpg

https://storage.googleapis.com/ygoprodeck.com/pics_small/27551.jpg

**Comment by usersina** [comment]
Noted, I will proceed to changing it right away.
I also want to add that the script does not go above 250kbps when downloading (within my network atleast) as it only uses one request.

**Comment by AlanOC91** [comment]
Perfect thanks! I appreciate it.
I should note that we keep the Google cloud server images up to date with our site images so they should always be 1:1

**Comment by usersina** [comment]
No problem.
Quick question though: Should I look for a way to limit the download speed from the Google cloud server ?

**Comment by AlanOC91** [comment]
I'll look into it but I think it should be ok. From what I remember, their cloud server has something like 500 times the threshold my site would be able to provide so I remember recalling it being something I need not worry about ever. So you should be ok but I'll look into it to be sure.
